### ISSUE TITLE
integrate `CUnion.jl`

### ISSUE THREAD

**Issue by inkydragon** [Gnimuc/CSyntax.jl#1]
- [azurefx/CUnion.jl: C-like unions for Julia.](https://github.com/azurefx/CUnion.jl)

**Comment by Gnimuc** [comment]
FYI, [CBinding.jl](https://github.com/analytech-solutions/CBinding.jl) provides a similar macro that supports custom alignment. 

I'm not a big fan of these two implementations because both CBinding.jl and CUnion.jl implement this feature with either cumbersome complicated macros or based on AST utility tools like MacroTools which will add tons of indirect deps to any c-wrapper-projects that need such a small feature. I'm wondering why it is so hard to interop with C unions in Julia. 

Here is the old school method(IIRC, it hasn't been changed since Julia-v0.4) that Julia doc tells:

> Packed structs and union declarations are not supported by Julia.

> You can get an approximation of a union if you know, a priori, the field that will have the greatest size (potentially including padding). When translating your fields to Julia, declare the Julia field to be only of that type.

The only info we need to know is **the greatest field size with correct padding**. With this info, we can declare the field to be only of an NTuple type of that size and imitate the behavior of a C union by overloading `Base.getproperty`. 

However, It looks like both CBinding.jl and CUnion.jl try to tackle the problem of finding the greatest field size or field padding from the Julia side. Wouldn't it be easier to directly query that info from a true C/C++ compiler like Clang? How about extracting the size, padding and offset info using Clang.jl and auto-generating "blob"-structs and corresponding methods for `Base.getproperty`?

**Comment by inkydragon** [comment]
- [尝试使用 libclang 提取 C Union 的信息 - 综合讨论区 / 语言特性及语义 - Julia中文社区](https://discourse.juliacn.com/t/topic/2744)

+ [clang_Type_getSizeOf](https://clang.llvm.org/doxygen/group__CINDEX__TYPES.html#ga027abe334546e80931905f31399d0a8b) ([CXType](https://clang.llvm.org/doxygen/structCXType.html) T) == [sizeof  - cppreference.com](https://en.cppreference.com/w/cpp/language/sizeof)
+ [clang_Type_getOffsetOf](https://clang.llvm.org/doxygen/group__CINDEX__TYPES.html#gab543536d5c18efb3e23a1b7903fb494d) ([CXType](https://clang.llvm.org/doxygen/structCXType.html) T, const char *S) == [offsetof - cppreference.com](https://en.cppreference.com/w/cpp/types/offsetof)
+ [clang_Type_getAlignOf](https://clang.llvm.org/doxygen/group__CINDEX__TYPES.html#gaee56de66c69ab5605fe47e7c52497e31) ([CXType](https://clang.llvm.org/doxygen/structCXType.html) T) == [offsetof - cppreference.com](https://en.cppreference.com/w/cpp/types/offsetof)

**Comment by Gnimuc** [comment]
I'm closing this as Clang.jl has implemented the workaround proposed in the comments above and `CUnion.jl` seems to be dead now.
